version: '3'
services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    command: ruby proxx_game.rb
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rspec
